
package demo01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HTFKServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HTFKServiceSoap {


    /**
     * 
     * @param xmlstr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PayMoney", action = "http://tempuri.org/PayMoney")
    @WebResult(name = "PayMoneyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PayMoney", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PayMoney")
    @ResponseWrapper(localName = "PayMoneyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PayMoneyResponse")
    public String payMoney(
            @WebParam(name = "xmlstr", targetNamespace = "http://tempuri.org/")
                    String xmlstr);

    /**
     * 
     * @param result
     * @param eventId
     * @param responseDesc
     * @param userName
     * @param operationTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ApproveResult", action = "http://tempuri.org/ApproveResult")
    @WebResult(name = "ApproveResultResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ApproveResult", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ApproveResult")
    @ResponseWrapper(localName = "ApproveResultResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ApproveResultResponse")
    public String approveResult(
            @WebParam(name = "eventId", targetNamespace = "http://tempuri.org/")
                    String eventId,
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "operationTime", targetNamespace = "http://tempuri.org/")
                    String operationTime,
            @WebParam(name = "result", targetNamespace = "http://tempuri.org/")
                    int result,
            @WebParam(name = "responseDesc", targetNamespace = "http://tempuri.org/")
                    String responseDesc);

}
