
package demo01;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HTFKService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://60.29.46.254:8060/Cbgl/WebService/HTFKService.asmx?wsdl")
public class HTFKService
    extends Service
{

    private final static URL HTFKSERVICE_WSDL_LOCATION;
    private final static WebServiceException HTFKSERVICE_EXCEPTION;
    private final static QName HTFKSERVICE_QNAME = new QName("http://tempuri.org/", "HTFKService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://60.29.46.254:8060/Cbgl/WebService/HTFKService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HTFKSERVICE_WSDL_LOCATION = url;
        HTFKSERVICE_EXCEPTION = e;
    }

    public HTFKService() {
        super(__getWsdlLocation(), HTFKSERVICE_QNAME);
    }

    public HTFKService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HTFKSERVICE_QNAME, features);
    }

    public HTFKService(URL wsdlLocation) {
        super(wsdlLocation, HTFKSERVICE_QNAME);
    }

    public HTFKService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HTFKSERVICE_QNAME, features);
    }

    public HTFKService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HTFKService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HTFKServiceSoap
     */
    @WebEndpoint(name = "HTFKServiceSoap")
    public HTFKServiceSoap getHTFKServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "HTFKServiceSoap"), HTFKServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HTFKServiceSoap
     */
    @WebEndpoint(name = "HTFKServiceSoap")
    public HTFKServiceSoap getHTFKServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "HTFKServiceSoap"), HTFKServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns HTFKServiceSoap
     */
    @WebEndpoint(name = "HTFKServiceSoap12")
    public HTFKServiceSoap getHTFKServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "HTFKServiceSoap12"), HTFKServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HTFKServiceSoap
     */
    @WebEndpoint(name = "HTFKServiceSoap12")
    public HTFKServiceSoap getHTFKServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "HTFKServiceSoap12"), HTFKServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HTFKSERVICE_EXCEPTION!= null) {
            throw HTFKSERVICE_EXCEPTION;
        }
        return HTFKSERVICE_WSDL_LOCATION;
    }

}
