package com.tbjj.portal.repository.api.entity;

import java.util.Date;

public class Contract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.id
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.event_id
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private Integer eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.company_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.contract_type
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String contractType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.apply_user_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String applyUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.apply_dept
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String applyDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.clauseItem_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String clauseitemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.item_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.contract_code
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String contractCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.contract_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String contractName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.jia_company
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String jiaCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.yi_company
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String yiCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.bing_company
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String bingCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.contract_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String contractMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.pay_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String payMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.total_pay_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String totalPayMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.apply_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String applyMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.pay_cause
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String payCause;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.pay_way
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String payWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.real_pay_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String realPayMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.pay_money_date
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private Date payMoneyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.apply_date
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private Date applyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.unit_id
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private String unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract.is_delete
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.id
     *
     * @return the value of portal_contract.id
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.id
     *
     * @param id the value for portal_contract.id
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.event_id
     *
     * @return the value of portal_contract.event_id
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.event_id
     *
     * @param eventId the value for portal_contract.event_id
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.company_name
     *
     * @return the value of portal_contract.company_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.company_name
     *
     * @param companyName the value for portal_contract.company_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.contract_type
     *
     * @return the value of portal_contract.contract_type
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getContractType() {
        return contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.contract_type
     *
     * @param contractType the value for portal_contract.contract_type
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setContractType(String contractType) {
        this.contractType = contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.apply_user_name
     *
     * @return the value of portal_contract.apply_user_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getApplyUserName() {
        return applyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.apply_user_name
     *
     * @param applyUserName the value for portal_contract.apply_user_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setApplyUserName(String applyUserName) {
        this.applyUserName = applyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.apply_dept
     *
     * @return the value of portal_contract.apply_dept
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getApplyDept() {
        return applyDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.apply_dept
     *
     * @param applyDept the value for portal_contract.apply_dept
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setApplyDept(String applyDept) {
        this.applyDept = applyDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.clauseItem_name
     *
     * @return the value of portal_contract.clauseItem_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getClauseitemName() {
        return clauseitemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.clauseItem_name
     *
     * @param clauseitemName the value for portal_contract.clauseItem_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setClauseitemName(String clauseitemName) {
        this.clauseitemName = clauseitemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.item_name
     *
     * @return the value of portal_contract.item_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.item_name
     *
     * @param itemName the value for portal_contract.item_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.contract_code
     *
     * @return the value of portal_contract.contract_code
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getContractCode() {
        return contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.contract_code
     *
     * @param contractCode the value for portal_contract.contract_code
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.contract_name
     *
     * @return the value of portal_contract.contract_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.contract_name
     *
     * @param contractName the value for portal_contract.contract_name
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.jia_company
     *
     * @return the value of portal_contract.jia_company
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getJiaCompany() {
        return jiaCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.jia_company
     *
     * @param jiaCompany the value for portal_contract.jia_company
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setJiaCompany(String jiaCompany) {
        this.jiaCompany = jiaCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.yi_company
     *
     * @return the value of portal_contract.yi_company
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getYiCompany() {
        return yiCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.yi_company
     *
     * @param yiCompany the value for portal_contract.yi_company
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setYiCompany(String yiCompany) {
        this.yiCompany = yiCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.bing_company
     *
     * @return the value of portal_contract.bing_company
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getBingCompany() {
        return bingCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.bing_company
     *
     * @param bingCompany the value for portal_contract.bing_company
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setBingCompany(String bingCompany) {
        this.bingCompany = bingCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.contract_money
     *
     * @return the value of portal_contract.contract_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getContractMoney() {
        return contractMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.contract_money
     *
     * @param contractMoney the value for portal_contract.contract_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setContractMoney(String contractMoney) {
        this.contractMoney = contractMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.pay_money
     *
     * @return the value of portal_contract.pay_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.pay_money
     *
     * @param payMoney the value for portal_contract.pay_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setPayMoney(String payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.total_pay_money
     *
     * @return the value of portal_contract.total_pay_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getTotalPayMoney() {
        return totalPayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.total_pay_money
     *
     * @param totalPayMoney the value for portal_contract.total_pay_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setTotalPayMoney(String totalPayMoney) {
        this.totalPayMoney = totalPayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.apply_money
     *
     * @return the value of portal_contract.apply_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getApplyMoney() {
        return applyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.apply_money
     *
     * @param applyMoney the value for portal_contract.apply_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setApplyMoney(String applyMoney) {
        this.applyMoney = applyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.pay_cause
     *
     * @return the value of portal_contract.pay_cause
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getPayCause() {
        return payCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.pay_cause
     *
     * @param payCause the value for portal_contract.pay_cause
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setPayCause(String payCause) {
        this.payCause = payCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.pay_way
     *
     * @return the value of portal_contract.pay_way
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.pay_way
     *
     * @param payWay the value for portal_contract.pay_way
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setPayWay(String payWay) {
        this.payWay = payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.real_pay_money
     *
     * @return the value of portal_contract.real_pay_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getRealPayMoney() {
        return realPayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.real_pay_money
     *
     * @param realPayMoney the value for portal_contract.real_pay_money
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setRealPayMoney(String realPayMoney) {
        this.realPayMoney = realPayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.pay_money_date
     *
     * @return the value of portal_contract.pay_money_date
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public Date getPayMoneyDate() {
        return payMoneyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.pay_money_date
     *
     * @param payMoneyDate the value for portal_contract.pay_money_date
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setPayMoneyDate(Date payMoneyDate) {
        this.payMoneyDate = payMoneyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.apply_date
     *
     * @return the value of portal_contract.apply_date
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.apply_date
     *
     * @param applyDate the value for portal_contract.apply_date
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.unit_id
     *
     * @return the value of portal_contract.unit_id
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.unit_id
     *
     * @param unitId the value for portal_contract.unit_id
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract.is_delete
     *
     * @return the value of portal_contract.is_delete
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract.is_delete
     *
     * @param isDelete the value for portal_contract.is_delete
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}