package com.tbjj.portal.repository.api.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContractExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public ContractExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEventIdIsNull() {
            addCriterion("event_id is null");
            return (Criteria) this;
        }

        public Criteria andEventIdIsNotNull() {
            addCriterion("event_id is not null");
            return (Criteria) this;
        }

        public Criteria andEventIdEqualTo(Integer value) {
            addCriterion("event_id =", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotEqualTo(Integer value) {
            addCriterion("event_id <>", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdGreaterThan(Integer value) {
            addCriterion("event_id >", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("event_id >=", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLessThan(Integer value) {
            addCriterion("event_id <", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLessThanOrEqualTo(Integer value) {
            addCriterion("event_id <=", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdIn(List<Integer> values) {
            addCriterion("event_id in", values, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotIn(List<Integer> values) {
            addCriterion("event_id not in", values, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdBetween(Integer value1, Integer value2) {
            addCriterion("event_id between", value1, value2, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotBetween(Integer value1, Integer value2) {
            addCriterion("event_id not between", value1, value2, "eventId");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andContractTypeIsNull() {
            addCriterion("contract_type is null");
            return (Criteria) this;
        }

        public Criteria andContractTypeIsNotNull() {
            addCriterion("contract_type is not null");
            return (Criteria) this;
        }

        public Criteria andContractTypeEqualTo(String value) {
            addCriterion("contract_type =", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotEqualTo(String value) {
            addCriterion("contract_type <>", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeGreaterThan(String value) {
            addCriterion("contract_type >", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeGreaterThanOrEqualTo(String value) {
            addCriterion("contract_type >=", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLessThan(String value) {
            addCriterion("contract_type <", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLessThanOrEqualTo(String value) {
            addCriterion("contract_type <=", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLike(String value) {
            addCriterion("contract_type like", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotLike(String value) {
            addCriterion("contract_type not like", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeIn(List<String> values) {
            addCriterion("contract_type in", values, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotIn(List<String> values) {
            addCriterion("contract_type not in", values, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeBetween(String value1, String value2) {
            addCriterion("contract_type between", value1, value2, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotBetween(String value1, String value2) {
            addCriterion("contract_type not between", value1, value2, "contractType");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIsNull() {
            addCriterion("apply_user_name is null");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIsNotNull() {
            addCriterion("apply_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameEqualTo(String value) {
            addCriterion("apply_user_name =", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotEqualTo(String value) {
            addCriterion("apply_user_name <>", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameGreaterThan(String value) {
            addCriterion("apply_user_name >", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("apply_user_name >=", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLessThan(String value) {
            addCriterion("apply_user_name <", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLessThanOrEqualTo(String value) {
            addCriterion("apply_user_name <=", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameLike(String value) {
            addCriterion("apply_user_name like", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotLike(String value) {
            addCriterion("apply_user_name not like", value, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameIn(List<String> values) {
            addCriterion("apply_user_name in", values, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotIn(List<String> values) {
            addCriterion("apply_user_name not in", values, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameBetween(String value1, String value2) {
            addCriterion("apply_user_name between", value1, value2, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyUserNameNotBetween(String value1, String value2) {
            addCriterion("apply_user_name not between", value1, value2, "applyUserName");
            return (Criteria) this;
        }

        public Criteria andApplyDeptIsNull() {
            addCriterion("apply_dept is null");
            return (Criteria) this;
        }

        public Criteria andApplyDeptIsNotNull() {
            addCriterion("apply_dept is not null");
            return (Criteria) this;
        }

        public Criteria andApplyDeptEqualTo(String value) {
            addCriterion("apply_dept =", value, "applyDept");
            return (Criteria) this;
        }

        public Criteria andApplyDeptNotEqualTo(String value) {
            addCriterion("apply_dept <>", value, "applyDept");
            return (Criteria) this;
        }

        public Criteria andApplyDeptGreaterThan(String value) {
            addCriterion("apply_dept >", value, "applyDept");
            return (Criteria) this;
        }

        public Criteria andApplyDeptGreaterThanOrEqualTo(String value) {
            addCriterion("apply_dept >=", value, "applyDept");
            return (Criteria) this;
        }

        public Criteria andApplyDeptLessThan(String value) {
            addCriterion("apply_dept <", value, "applyDept");
            return (Criteria) this;
        }

        public Criteria andApplyDeptLessThanOrEqualTo(String value) {
            addCriterion("apply_dept <=", value, "applyDept");
            return (Criteria) this;
        }

        public Criteria andApplyDeptLike(String value) {
            addCriterion("apply_dept like", value, "applyDept");
            return (Criteria) this;
        }

        public Criteria andApplyDeptNotLike(String value) {
            addCriterion("apply_dept not like", value, "applyDept");
            return (Criteria) this;
        }

        public Criteria andApplyDeptIn(List<String> values) {
            addCriterion("apply_dept in", values, "applyDept");
            return (Criteria) this;
        }

        public Criteria andApplyDeptNotIn(List<String> values) {
            addCriterion("apply_dept not in", values, "applyDept");
            return (Criteria) this;
        }

        public Criteria andApplyDeptBetween(String value1, String value2) {
            addCriterion("apply_dept between", value1, value2, "applyDept");
            return (Criteria) this;
        }

        public Criteria andApplyDeptNotBetween(String value1, String value2) {
            addCriterion("apply_dept not between", value1, value2, "applyDept");
            return (Criteria) this;
        }

        public Criteria andClauseitemNameIsNull() {
            addCriterion("clauseItem_name is null");
            return (Criteria) this;
        }

        public Criteria andClauseitemNameIsNotNull() {
            addCriterion("clauseItem_name is not null");
            return (Criteria) this;
        }

        public Criteria andClauseitemNameEqualTo(String value) {
            addCriterion("clauseItem_name =", value, "clauseitemName");
            return (Criteria) this;
        }

        public Criteria andClauseitemNameNotEqualTo(String value) {
            addCriterion("clauseItem_name <>", value, "clauseitemName");
            return (Criteria) this;
        }

        public Criteria andClauseitemNameGreaterThan(String value) {
            addCriterion("clauseItem_name >", value, "clauseitemName");
            return (Criteria) this;
        }

        public Criteria andClauseitemNameGreaterThanOrEqualTo(String value) {
            addCriterion("clauseItem_name >=", value, "clauseitemName");
            return (Criteria) this;
        }

        public Criteria andClauseitemNameLessThan(String value) {
            addCriterion("clauseItem_name <", value, "clauseitemName");
            return (Criteria) this;
        }

        public Criteria andClauseitemNameLessThanOrEqualTo(String value) {
            addCriterion("clauseItem_name <=", value, "clauseitemName");
            return (Criteria) this;
        }

        public Criteria andClauseitemNameLike(String value) {
            addCriterion("clauseItem_name like", value, "clauseitemName");
            return (Criteria) this;
        }

        public Criteria andClauseitemNameNotLike(String value) {
            addCriterion("clauseItem_name not like", value, "clauseitemName");
            return (Criteria) this;
        }

        public Criteria andClauseitemNameIn(List<String> values) {
            addCriterion("clauseItem_name in", values, "clauseitemName");
            return (Criteria) this;
        }

        public Criteria andClauseitemNameNotIn(List<String> values) {
            addCriterion("clauseItem_name not in", values, "clauseitemName");
            return (Criteria) this;
        }

        public Criteria andClauseitemNameBetween(String value1, String value2) {
            addCriterion("clauseItem_name between", value1, value2, "clauseitemName");
            return (Criteria) this;
        }

        public Criteria andClauseitemNameNotBetween(String value1, String value2) {
            addCriterion("clauseItem_name not between", value1, value2, "clauseitemName");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNull() {
            addCriterion("item_name is null");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNotNull() {
            addCriterion("item_name is not null");
            return (Criteria) this;
        }

        public Criteria andItemNameEqualTo(String value) {
            addCriterion("item_name =", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotEqualTo(String value) {
            addCriterion("item_name <>", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThan(String value) {
            addCriterion("item_name >", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThanOrEqualTo(String value) {
            addCriterion("item_name >=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThan(String value) {
            addCriterion("item_name <", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThanOrEqualTo(String value) {
            addCriterion("item_name <=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLike(String value) {
            addCriterion("item_name like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotLike(String value) {
            addCriterion("item_name not like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameIn(List<String> values) {
            addCriterion("item_name in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotIn(List<String> values) {
            addCriterion("item_name not in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameBetween(String value1, String value2) {
            addCriterion("item_name between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotBetween(String value1, String value2) {
            addCriterion("item_name not between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andContractCodeIsNull() {
            addCriterion("contract_code is null");
            return (Criteria) this;
        }

        public Criteria andContractCodeIsNotNull() {
            addCriterion("contract_code is not null");
            return (Criteria) this;
        }

        public Criteria andContractCodeEqualTo(String value) {
            addCriterion("contract_code =", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotEqualTo(String value) {
            addCriterion("contract_code <>", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeGreaterThan(String value) {
            addCriterion("contract_code >", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeGreaterThanOrEqualTo(String value) {
            addCriterion("contract_code >=", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeLessThan(String value) {
            addCriterion("contract_code <", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeLessThanOrEqualTo(String value) {
            addCriterion("contract_code <=", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeLike(String value) {
            addCriterion("contract_code like", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotLike(String value) {
            addCriterion("contract_code not like", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeIn(List<String> values) {
            addCriterion("contract_code in", values, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotIn(List<String> values) {
            addCriterion("contract_code not in", values, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeBetween(String value1, String value2) {
            addCriterion("contract_code between", value1, value2, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotBetween(String value1, String value2) {
            addCriterion("contract_code not between", value1, value2, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractNameIsNull() {
            addCriterion("contract_name is null");
            return (Criteria) this;
        }

        public Criteria andContractNameIsNotNull() {
            addCriterion("contract_name is not null");
            return (Criteria) this;
        }

        public Criteria andContractNameEqualTo(String value) {
            addCriterion("contract_name =", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotEqualTo(String value) {
            addCriterion("contract_name <>", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameGreaterThan(String value) {
            addCriterion("contract_name >", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameGreaterThanOrEqualTo(String value) {
            addCriterion("contract_name >=", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLessThan(String value) {
            addCriterion("contract_name <", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLessThanOrEqualTo(String value) {
            addCriterion("contract_name <=", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLike(String value) {
            addCriterion("contract_name like", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotLike(String value) {
            addCriterion("contract_name not like", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameIn(List<String> values) {
            addCriterion("contract_name in", values, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotIn(List<String> values) {
            addCriterion("contract_name not in", values, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameBetween(String value1, String value2) {
            addCriterion("contract_name between", value1, value2, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotBetween(String value1, String value2) {
            addCriterion("contract_name not between", value1, value2, "contractName");
            return (Criteria) this;
        }

        public Criteria andJiaCompanyIsNull() {
            addCriterion("jia_company is null");
            return (Criteria) this;
        }

        public Criteria andJiaCompanyIsNotNull() {
            addCriterion("jia_company is not null");
            return (Criteria) this;
        }

        public Criteria andJiaCompanyEqualTo(String value) {
            addCriterion("jia_company =", value, "jiaCompany");
            return (Criteria) this;
        }

        public Criteria andJiaCompanyNotEqualTo(String value) {
            addCriterion("jia_company <>", value, "jiaCompany");
            return (Criteria) this;
        }

        public Criteria andJiaCompanyGreaterThan(String value) {
            addCriterion("jia_company >", value, "jiaCompany");
            return (Criteria) this;
        }

        public Criteria andJiaCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("jia_company >=", value, "jiaCompany");
            return (Criteria) this;
        }

        public Criteria andJiaCompanyLessThan(String value) {
            addCriterion("jia_company <", value, "jiaCompany");
            return (Criteria) this;
        }

        public Criteria andJiaCompanyLessThanOrEqualTo(String value) {
            addCriterion("jia_company <=", value, "jiaCompany");
            return (Criteria) this;
        }

        public Criteria andJiaCompanyLike(String value) {
            addCriterion("jia_company like", value, "jiaCompany");
            return (Criteria) this;
        }

        public Criteria andJiaCompanyNotLike(String value) {
            addCriterion("jia_company not like", value, "jiaCompany");
            return (Criteria) this;
        }

        public Criteria andJiaCompanyIn(List<String> values) {
            addCriterion("jia_company in", values, "jiaCompany");
            return (Criteria) this;
        }

        public Criteria andJiaCompanyNotIn(List<String> values) {
            addCriterion("jia_company not in", values, "jiaCompany");
            return (Criteria) this;
        }

        public Criteria andJiaCompanyBetween(String value1, String value2) {
            addCriterion("jia_company between", value1, value2, "jiaCompany");
            return (Criteria) this;
        }

        public Criteria andJiaCompanyNotBetween(String value1, String value2) {
            addCriterion("jia_company not between", value1, value2, "jiaCompany");
            return (Criteria) this;
        }

        public Criteria andYiCompanyIsNull() {
            addCriterion("yi_company is null");
            return (Criteria) this;
        }

        public Criteria andYiCompanyIsNotNull() {
            addCriterion("yi_company is not null");
            return (Criteria) this;
        }

        public Criteria andYiCompanyEqualTo(String value) {
            addCriterion("yi_company =", value, "yiCompany");
            return (Criteria) this;
        }

        public Criteria andYiCompanyNotEqualTo(String value) {
            addCriterion("yi_company <>", value, "yiCompany");
            return (Criteria) this;
        }

        public Criteria andYiCompanyGreaterThan(String value) {
            addCriterion("yi_company >", value, "yiCompany");
            return (Criteria) this;
        }

        public Criteria andYiCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("yi_company >=", value, "yiCompany");
            return (Criteria) this;
        }

        public Criteria andYiCompanyLessThan(String value) {
            addCriterion("yi_company <", value, "yiCompany");
            return (Criteria) this;
        }

        public Criteria andYiCompanyLessThanOrEqualTo(String value) {
            addCriterion("yi_company <=", value, "yiCompany");
            return (Criteria) this;
        }

        public Criteria andYiCompanyLike(String value) {
            addCriterion("yi_company like", value, "yiCompany");
            return (Criteria) this;
        }

        public Criteria andYiCompanyNotLike(String value) {
            addCriterion("yi_company not like", value, "yiCompany");
            return (Criteria) this;
        }

        public Criteria andYiCompanyIn(List<String> values) {
            addCriterion("yi_company in", values, "yiCompany");
            return (Criteria) this;
        }

        public Criteria andYiCompanyNotIn(List<String> values) {
            addCriterion("yi_company not in", values, "yiCompany");
            return (Criteria) this;
        }

        public Criteria andYiCompanyBetween(String value1, String value2) {
            addCriterion("yi_company between", value1, value2, "yiCompany");
            return (Criteria) this;
        }

        public Criteria andYiCompanyNotBetween(String value1, String value2) {
            addCriterion("yi_company not between", value1, value2, "yiCompany");
            return (Criteria) this;
        }

        public Criteria andBingCompanyIsNull() {
            addCriterion("bing_company is null");
            return (Criteria) this;
        }

        public Criteria andBingCompanyIsNotNull() {
            addCriterion("bing_company is not null");
            return (Criteria) this;
        }

        public Criteria andBingCompanyEqualTo(String value) {
            addCriterion("bing_company =", value, "bingCompany");
            return (Criteria) this;
        }

        public Criteria andBingCompanyNotEqualTo(String value) {
            addCriterion("bing_company <>", value, "bingCompany");
            return (Criteria) this;
        }

        public Criteria andBingCompanyGreaterThan(String value) {
            addCriterion("bing_company >", value, "bingCompany");
            return (Criteria) this;
        }

        public Criteria andBingCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("bing_company >=", value, "bingCompany");
            return (Criteria) this;
        }

        public Criteria andBingCompanyLessThan(String value) {
            addCriterion("bing_company <", value, "bingCompany");
            return (Criteria) this;
        }

        public Criteria andBingCompanyLessThanOrEqualTo(String value) {
            addCriterion("bing_company <=", value, "bingCompany");
            return (Criteria) this;
        }

        public Criteria andBingCompanyLike(String value) {
            addCriterion("bing_company like", value, "bingCompany");
            return (Criteria) this;
        }

        public Criteria andBingCompanyNotLike(String value) {
            addCriterion("bing_company not like", value, "bingCompany");
            return (Criteria) this;
        }

        public Criteria andBingCompanyIn(List<String> values) {
            addCriterion("bing_company in", values, "bingCompany");
            return (Criteria) this;
        }

        public Criteria andBingCompanyNotIn(List<String> values) {
            addCriterion("bing_company not in", values, "bingCompany");
            return (Criteria) this;
        }

        public Criteria andBingCompanyBetween(String value1, String value2) {
            addCriterion("bing_company between", value1, value2, "bingCompany");
            return (Criteria) this;
        }

        public Criteria andBingCompanyNotBetween(String value1, String value2) {
            addCriterion("bing_company not between", value1, value2, "bingCompany");
            return (Criteria) this;
        }

        public Criteria andContractMoneyIsNull() {
            addCriterion("contract_money is null");
            return (Criteria) this;
        }

        public Criteria andContractMoneyIsNotNull() {
            addCriterion("contract_money is not null");
            return (Criteria) this;
        }

        public Criteria andContractMoneyEqualTo(String value) {
            addCriterion("contract_money =", value, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyNotEqualTo(String value) {
            addCriterion("contract_money <>", value, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyGreaterThan(String value) {
            addCriterion("contract_money >", value, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("contract_money >=", value, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyLessThan(String value) {
            addCriterion("contract_money <", value, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyLessThanOrEqualTo(String value) {
            addCriterion("contract_money <=", value, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyLike(String value) {
            addCriterion("contract_money like", value, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyNotLike(String value) {
            addCriterion("contract_money not like", value, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyIn(List<String> values) {
            addCriterion("contract_money in", values, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyNotIn(List<String> values) {
            addCriterion("contract_money not in", values, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyBetween(String value1, String value2) {
            addCriterion("contract_money between", value1, value2, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyNotBetween(String value1, String value2) {
            addCriterion("contract_money not between", value1, value2, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyIsNull() {
            addCriterion("pay_money is null");
            return (Criteria) this;
        }

        public Criteria andPayMoneyIsNotNull() {
            addCriterion("pay_money is not null");
            return (Criteria) this;
        }

        public Criteria andPayMoneyEqualTo(String value) {
            addCriterion("pay_money =", value, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyNotEqualTo(String value) {
            addCriterion("pay_money <>", value, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyGreaterThan(String value) {
            addCriterion("pay_money >", value, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("pay_money >=", value, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyLessThan(String value) {
            addCriterion("pay_money <", value, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyLessThanOrEqualTo(String value) {
            addCriterion("pay_money <=", value, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyLike(String value) {
            addCriterion("pay_money like", value, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyNotLike(String value) {
            addCriterion("pay_money not like", value, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyIn(List<String> values) {
            addCriterion("pay_money in", values, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyNotIn(List<String> values) {
            addCriterion("pay_money not in", values, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyBetween(String value1, String value2) {
            addCriterion("pay_money between", value1, value2, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyNotBetween(String value1, String value2) {
            addCriterion("pay_money not between", value1, value2, "payMoney");
            return (Criteria) this;
        }

        public Criteria andTotalPayMoneyIsNull() {
            addCriterion("total_pay_money is null");
            return (Criteria) this;
        }

        public Criteria andTotalPayMoneyIsNotNull() {
            addCriterion("total_pay_money is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPayMoneyEqualTo(String value) {
            addCriterion("total_pay_money =", value, "totalPayMoney");
            return (Criteria) this;
        }

        public Criteria andTotalPayMoneyNotEqualTo(String value) {
            addCriterion("total_pay_money <>", value, "totalPayMoney");
            return (Criteria) this;
        }

        public Criteria andTotalPayMoneyGreaterThan(String value) {
            addCriterion("total_pay_money >", value, "totalPayMoney");
            return (Criteria) this;
        }

        public Criteria andTotalPayMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("total_pay_money >=", value, "totalPayMoney");
            return (Criteria) this;
        }

        public Criteria andTotalPayMoneyLessThan(String value) {
            addCriterion("total_pay_money <", value, "totalPayMoney");
            return (Criteria) this;
        }

        public Criteria andTotalPayMoneyLessThanOrEqualTo(String value) {
            addCriterion("total_pay_money <=", value, "totalPayMoney");
            return (Criteria) this;
        }

        public Criteria andTotalPayMoneyLike(String value) {
            addCriterion("total_pay_money like", value, "totalPayMoney");
            return (Criteria) this;
        }

        public Criteria andTotalPayMoneyNotLike(String value) {
            addCriterion("total_pay_money not like", value, "totalPayMoney");
            return (Criteria) this;
        }

        public Criteria andTotalPayMoneyIn(List<String> values) {
            addCriterion("total_pay_money in", values, "totalPayMoney");
            return (Criteria) this;
        }

        public Criteria andTotalPayMoneyNotIn(List<String> values) {
            addCriterion("total_pay_money not in", values, "totalPayMoney");
            return (Criteria) this;
        }

        public Criteria andTotalPayMoneyBetween(String value1, String value2) {
            addCriterion("total_pay_money between", value1, value2, "totalPayMoney");
            return (Criteria) this;
        }

        public Criteria andTotalPayMoneyNotBetween(String value1, String value2) {
            addCriterion("total_pay_money not between", value1, value2, "totalPayMoney");
            return (Criteria) this;
        }

        public Criteria andApplyMoneyIsNull() {
            addCriterion("apply_money is null");
            return (Criteria) this;
        }

        public Criteria andApplyMoneyIsNotNull() {
            addCriterion("apply_money is not null");
            return (Criteria) this;
        }

        public Criteria andApplyMoneyEqualTo(String value) {
            addCriterion("apply_money =", value, "applyMoney");
            return (Criteria) this;
        }

        public Criteria andApplyMoneyNotEqualTo(String value) {
            addCriterion("apply_money <>", value, "applyMoney");
            return (Criteria) this;
        }

        public Criteria andApplyMoneyGreaterThan(String value) {
            addCriterion("apply_money >", value, "applyMoney");
            return (Criteria) this;
        }

        public Criteria andApplyMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("apply_money >=", value, "applyMoney");
            return (Criteria) this;
        }

        public Criteria andApplyMoneyLessThan(String value) {
            addCriterion("apply_money <", value, "applyMoney");
            return (Criteria) this;
        }

        public Criteria andApplyMoneyLessThanOrEqualTo(String value) {
            addCriterion("apply_money <=", value, "applyMoney");
            return (Criteria) this;
        }

        public Criteria andApplyMoneyLike(String value) {
            addCriterion("apply_money like", value, "applyMoney");
            return (Criteria) this;
        }

        public Criteria andApplyMoneyNotLike(String value) {
            addCriterion("apply_money not like", value, "applyMoney");
            return (Criteria) this;
        }

        public Criteria andApplyMoneyIn(List<String> values) {
            addCriterion("apply_money in", values, "applyMoney");
            return (Criteria) this;
        }

        public Criteria andApplyMoneyNotIn(List<String> values) {
            addCriterion("apply_money not in", values, "applyMoney");
            return (Criteria) this;
        }

        public Criteria andApplyMoneyBetween(String value1, String value2) {
            addCriterion("apply_money between", value1, value2, "applyMoney");
            return (Criteria) this;
        }

        public Criteria andApplyMoneyNotBetween(String value1, String value2) {
            addCriterion("apply_money not between", value1, value2, "applyMoney");
            return (Criteria) this;
        }

        public Criteria andPayCauseIsNull() {
            addCriterion("pay_cause is null");
            return (Criteria) this;
        }

        public Criteria andPayCauseIsNotNull() {
            addCriterion("pay_cause is not null");
            return (Criteria) this;
        }

        public Criteria andPayCauseEqualTo(String value) {
            addCriterion("pay_cause =", value, "payCause");
            return (Criteria) this;
        }

        public Criteria andPayCauseNotEqualTo(String value) {
            addCriterion("pay_cause <>", value, "payCause");
            return (Criteria) this;
        }

        public Criteria andPayCauseGreaterThan(String value) {
            addCriterion("pay_cause >", value, "payCause");
            return (Criteria) this;
        }

        public Criteria andPayCauseGreaterThanOrEqualTo(String value) {
            addCriterion("pay_cause >=", value, "payCause");
            return (Criteria) this;
        }

        public Criteria andPayCauseLessThan(String value) {
            addCriterion("pay_cause <", value, "payCause");
            return (Criteria) this;
        }

        public Criteria andPayCauseLessThanOrEqualTo(String value) {
            addCriterion("pay_cause <=", value, "payCause");
            return (Criteria) this;
        }

        public Criteria andPayCauseLike(String value) {
            addCriterion("pay_cause like", value, "payCause");
            return (Criteria) this;
        }

        public Criteria andPayCauseNotLike(String value) {
            addCriterion("pay_cause not like", value, "payCause");
            return (Criteria) this;
        }

        public Criteria andPayCauseIn(List<String> values) {
            addCriterion("pay_cause in", values, "payCause");
            return (Criteria) this;
        }

        public Criteria andPayCauseNotIn(List<String> values) {
            addCriterion("pay_cause not in", values, "payCause");
            return (Criteria) this;
        }

        public Criteria andPayCauseBetween(String value1, String value2) {
            addCriterion("pay_cause between", value1, value2, "payCause");
            return (Criteria) this;
        }

        public Criteria andPayCauseNotBetween(String value1, String value2) {
            addCriterion("pay_cause not between", value1, value2, "payCause");
            return (Criteria) this;
        }

        public Criteria andPayWayIsNull() {
            addCriterion("pay_way is null");
            return (Criteria) this;
        }

        public Criteria andPayWayIsNotNull() {
            addCriterion("pay_way is not null");
            return (Criteria) this;
        }

        public Criteria andPayWayEqualTo(String value) {
            addCriterion("pay_way =", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayNotEqualTo(String value) {
            addCriterion("pay_way <>", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayGreaterThan(String value) {
            addCriterion("pay_way >", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayGreaterThanOrEqualTo(String value) {
            addCriterion("pay_way >=", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayLessThan(String value) {
            addCriterion("pay_way <", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayLessThanOrEqualTo(String value) {
            addCriterion("pay_way <=", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayLike(String value) {
            addCriterion("pay_way like", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayNotLike(String value) {
            addCriterion("pay_way not like", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayIn(List<String> values) {
            addCriterion("pay_way in", values, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayNotIn(List<String> values) {
            addCriterion("pay_way not in", values, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayBetween(String value1, String value2) {
            addCriterion("pay_way between", value1, value2, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayNotBetween(String value1, String value2) {
            addCriterion("pay_way not between", value1, value2, "payWay");
            return (Criteria) this;
        }

        public Criteria andRealPayMoneyIsNull() {
            addCriterion("real_pay_money is null");
            return (Criteria) this;
        }

        public Criteria andRealPayMoneyIsNotNull() {
            addCriterion("real_pay_money is not null");
            return (Criteria) this;
        }

        public Criteria andRealPayMoneyEqualTo(String value) {
            addCriterion("real_pay_money =", value, "realPayMoney");
            return (Criteria) this;
        }

        public Criteria andRealPayMoneyNotEqualTo(String value) {
            addCriterion("real_pay_money <>", value, "realPayMoney");
            return (Criteria) this;
        }

        public Criteria andRealPayMoneyGreaterThan(String value) {
            addCriterion("real_pay_money >", value, "realPayMoney");
            return (Criteria) this;
        }

        public Criteria andRealPayMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("real_pay_money >=", value, "realPayMoney");
            return (Criteria) this;
        }

        public Criteria andRealPayMoneyLessThan(String value) {
            addCriterion("real_pay_money <", value, "realPayMoney");
            return (Criteria) this;
        }

        public Criteria andRealPayMoneyLessThanOrEqualTo(String value) {
            addCriterion("real_pay_money <=", value, "realPayMoney");
            return (Criteria) this;
        }

        public Criteria andRealPayMoneyLike(String value) {
            addCriterion("real_pay_money like", value, "realPayMoney");
            return (Criteria) this;
        }

        public Criteria andRealPayMoneyNotLike(String value) {
            addCriterion("real_pay_money not like", value, "realPayMoney");
            return (Criteria) this;
        }

        public Criteria andRealPayMoneyIn(List<String> values) {
            addCriterion("real_pay_money in", values, "realPayMoney");
            return (Criteria) this;
        }

        public Criteria andRealPayMoneyNotIn(List<String> values) {
            addCriterion("real_pay_money not in", values, "realPayMoney");
            return (Criteria) this;
        }

        public Criteria andRealPayMoneyBetween(String value1, String value2) {
            addCriterion("real_pay_money between", value1, value2, "realPayMoney");
            return (Criteria) this;
        }

        public Criteria andRealPayMoneyNotBetween(String value1, String value2) {
            addCriterion("real_pay_money not between", value1, value2, "realPayMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyDateIsNull() {
            addCriterion("pay_money_date is null");
            return (Criteria) this;
        }

        public Criteria andPayMoneyDateIsNotNull() {
            addCriterion("pay_money_date is not null");
            return (Criteria) this;
        }

        public Criteria andPayMoneyDateEqualTo(Date value) {
            addCriterion("pay_money_date =", value, "payMoneyDate");
            return (Criteria) this;
        }

        public Criteria andPayMoneyDateNotEqualTo(Date value) {
            addCriterion("pay_money_date <>", value, "payMoneyDate");
            return (Criteria) this;
        }

        public Criteria andPayMoneyDateGreaterThan(Date value) {
            addCriterion("pay_money_date >", value, "payMoneyDate");
            return (Criteria) this;
        }

        public Criteria andPayMoneyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("pay_money_date >=", value, "payMoneyDate");
            return (Criteria) this;
        }

        public Criteria andPayMoneyDateLessThan(Date value) {
            addCriterion("pay_money_date <", value, "payMoneyDate");
            return (Criteria) this;
        }

        public Criteria andPayMoneyDateLessThanOrEqualTo(Date value) {
            addCriterion("pay_money_date <=", value, "payMoneyDate");
            return (Criteria) this;
        }

        public Criteria andPayMoneyDateIn(List<Date> values) {
            addCriterion("pay_money_date in", values, "payMoneyDate");
            return (Criteria) this;
        }

        public Criteria andPayMoneyDateNotIn(List<Date> values) {
            addCriterion("pay_money_date not in", values, "payMoneyDate");
            return (Criteria) this;
        }

        public Criteria andPayMoneyDateBetween(Date value1, Date value2) {
            addCriterion("pay_money_date between", value1, value2, "payMoneyDate");
            return (Criteria) this;
        }

        public Criteria andPayMoneyDateNotBetween(Date value1, Date value2) {
            addCriterion("pay_money_date not between", value1, value2, "payMoneyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateIsNull() {
            addCriterion("apply_date is null");
            return (Criteria) this;
        }

        public Criteria andApplyDateIsNotNull() {
            addCriterion("apply_date is not null");
            return (Criteria) this;
        }

        public Criteria andApplyDateEqualTo(Date value) {
            addCriterion("apply_date =", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotEqualTo(Date value) {
            addCriterion("apply_date <>", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateGreaterThan(Date value) {
            addCriterion("apply_date >", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("apply_date >=", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateLessThan(Date value) {
            addCriterion("apply_date <", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateLessThanOrEqualTo(Date value) {
            addCriterion("apply_date <=", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateIn(List<Date> values) {
            addCriterion("apply_date in", values, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotIn(List<Date> values) {
            addCriterion("apply_date not in", values, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateBetween(Date value1, Date value2) {
            addCriterion("apply_date between", value1, value2, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotBetween(Date value1, Date value2) {
            addCriterion("apply_date not between", value1, value2, "applyDate");
            return (Criteria) this;
        }

        public Criteria andUnitIdIsNull() {
            addCriterion("unit_id is null");
            return (Criteria) this;
        }

        public Criteria andUnitIdIsNotNull() {
            addCriterion("unit_id is not null");
            return (Criteria) this;
        }

        public Criteria andUnitIdEqualTo(String value) {
            addCriterion("unit_id =", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotEqualTo(String value) {
            addCriterion("unit_id <>", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdGreaterThan(String value) {
            addCriterion("unit_id >", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdGreaterThanOrEqualTo(String value) {
            addCriterion("unit_id >=", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdLessThan(String value) {
            addCriterion("unit_id <", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdLessThanOrEqualTo(String value) {
            addCriterion("unit_id <=", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdLike(String value) {
            addCriterion("unit_id like", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotLike(String value) {
            addCriterion("unit_id not like", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdIn(List<String> values) {
            addCriterion("unit_id in", values, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotIn(List<String> values) {
            addCriterion("unit_id not in", values, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdBetween(String value1, String value2) {
            addCriterion("unit_id between", value1, value2, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotBetween(String value1, String value2) {
            addCriterion("unit_id not between", value1, value2, "unitId");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Byte value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Byte value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Byte value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Byte value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Byte value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Byte> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Byte> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Byte value1, Byte value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Byte value1, Byte value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_contract
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 01 17:07:11 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_contract
     *
     * @mbg.generated Thu Mar 01 17:07:11 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}