package com.tbjj.portal.repository.api.entity;

import java.util.ArrayList;
import java.util.List;

public class ContractTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public ContractTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andJqCodeIsNull() {
            addCriterion("jq_code is null");
            return (Criteria) this;
        }

        public Criteria andJqCodeIsNotNull() {
            addCriterion("jq_code is not null");
            return (Criteria) this;
        }

        public Criteria andJqCodeEqualTo(String value) {
            addCriterion("jq_code =", value, "jqCode");
            return (Criteria) this;
        }

        public Criteria andJqCodeNotEqualTo(String value) {
            addCriterion("jq_code <>", value, "jqCode");
            return (Criteria) this;
        }

        public Criteria andJqCodeGreaterThan(String value) {
            addCriterion("jq_code >", value, "jqCode");
            return (Criteria) this;
        }

        public Criteria andJqCodeGreaterThanOrEqualTo(String value) {
            addCriterion("jq_code >=", value, "jqCode");
            return (Criteria) this;
        }

        public Criteria andJqCodeLessThan(String value) {
            addCriterion("jq_code <", value, "jqCode");
            return (Criteria) this;
        }

        public Criteria andJqCodeLessThanOrEqualTo(String value) {
            addCriterion("jq_code <=", value, "jqCode");
            return (Criteria) this;
        }

        public Criteria andJqCodeLike(String value) {
            addCriterion("jq_code like", value, "jqCode");
            return (Criteria) this;
        }

        public Criteria andJqCodeNotLike(String value) {
            addCriterion("jq_code not like", value, "jqCode");
            return (Criteria) this;
        }

        public Criteria andJqCodeIn(List<String> values) {
            addCriterion("jq_code in", values, "jqCode");
            return (Criteria) this;
        }

        public Criteria andJqCodeNotIn(List<String> values) {
            addCriterion("jq_code not in", values, "jqCode");
            return (Criteria) this;
        }

        public Criteria andJqCodeBetween(String value1, String value2) {
            addCriterion("jq_code between", value1, value2, "jqCode");
            return (Criteria) this;
        }

        public Criteria andJqCodeNotBetween(String value1, String value2) {
            addCriterion("jq_code not between", value1, value2, "jqCode");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andContractNameIsNull() {
            addCriterion("contract_name is null");
            return (Criteria) this;
        }

        public Criteria andContractNameIsNotNull() {
            addCriterion("contract_name is not null");
            return (Criteria) this;
        }

        public Criteria andContractNameEqualTo(String value) {
            addCriterion("contract_name =", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotEqualTo(String value) {
            addCriterion("contract_name <>", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameGreaterThan(String value) {
            addCriterion("contract_name >", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameGreaterThanOrEqualTo(String value) {
            addCriterion("contract_name >=", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLessThan(String value) {
            addCriterion("contract_name <", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLessThanOrEqualTo(String value) {
            addCriterion("contract_name <=", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLike(String value) {
            addCriterion("contract_name like", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotLike(String value) {
            addCriterion("contract_name not like", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameIn(List<String> values) {
            addCriterion("contract_name in", values, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotIn(List<String> values) {
            addCriterion("contract_name not in", values, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameBetween(String value1, String value2) {
            addCriterion("contract_name between", value1, value2, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotBetween(String value1, String value2) {
            addCriterion("contract_name not between", value1, value2, "contractName");
            return (Criteria) this;
        }

        public Criteria andMyCodeIsNull() {
            addCriterion("my_code is null");
            return (Criteria) this;
        }

        public Criteria andMyCodeIsNotNull() {
            addCriterion("my_code is not null");
            return (Criteria) this;
        }

        public Criteria andMyCodeEqualTo(String value) {
            addCriterion("my_code =", value, "myCode");
            return (Criteria) this;
        }

        public Criteria andMyCodeNotEqualTo(String value) {
            addCriterion("my_code <>", value, "myCode");
            return (Criteria) this;
        }

        public Criteria andMyCodeGreaterThan(String value) {
            addCriterion("my_code >", value, "myCode");
            return (Criteria) this;
        }

        public Criteria andMyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("my_code >=", value, "myCode");
            return (Criteria) this;
        }

        public Criteria andMyCodeLessThan(String value) {
            addCriterion("my_code <", value, "myCode");
            return (Criteria) this;
        }

        public Criteria andMyCodeLessThanOrEqualTo(String value) {
            addCriterion("my_code <=", value, "myCode");
            return (Criteria) this;
        }

        public Criteria andMyCodeLike(String value) {
            addCriterion("my_code like", value, "myCode");
            return (Criteria) this;
        }

        public Criteria andMyCodeNotLike(String value) {
            addCriterion("my_code not like", value, "myCode");
            return (Criteria) this;
        }

        public Criteria andMyCodeIn(List<String> values) {
            addCriterion("my_code in", values, "myCode");
            return (Criteria) this;
        }

        public Criteria andMyCodeNotIn(List<String> values) {
            addCriterion("my_code not in", values, "myCode");
            return (Criteria) this;
        }

        public Criteria andMyCodeBetween(String value1, String value2) {
            addCriterion("my_code between", value1, value2, "myCode");
            return (Criteria) this;
        }

        public Criteria andMyCodeNotBetween(String value1, String value2) {
            addCriterion("my_code not between", value1, value2, "myCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_contract_type
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 15 15:38:11 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_contract_type
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}