package com.tbjj.portal.repository.api.entity;

public class ContractType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract_type.id
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract_type.jq_code
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    private String jqCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract_type.company_name
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract_type.contract_name
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    private String contractName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_contract_type.my_code
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    private String myCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract_type.id
     *
     * @return the value of portal_contract_type.id
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract_type.id
     *
     * @param id the value for portal_contract_type.id
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract_type.jq_code
     *
     * @return the value of portal_contract_type.jq_code
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public String getJqCode() {
        return jqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract_type.jq_code
     *
     * @param jqCode the value for portal_contract_type.jq_code
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public void setJqCode(String jqCode) {
        this.jqCode = jqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract_type.company_name
     *
     * @return the value of portal_contract_type.company_name
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract_type.company_name
     *
     * @param companyName the value for portal_contract_type.company_name
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract_type.contract_name
     *
     * @return the value of portal_contract_type.contract_name
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract_type.contract_name
     *
     * @param contractName the value for portal_contract_type.contract_name
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_contract_type.my_code
     *
     * @return the value of portal_contract_type.my_code
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public String getMyCode() {
        return myCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_contract_type.my_code
     *
     * @param myCode the value for portal_contract_type.my_code
     *
     * @mbg.generated Thu Mar 15 15:38:11 CST 2018
     */
    public void setMyCode(String myCode) {
        this.myCode = myCode;
    }
}