package com.tbjj.portal.repository.api.entity;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_employee.id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_employee.user_name
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_employee.password
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_employee.name
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_employee.mobile
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_employee.department_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_employee.is_delete
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_employee.token
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_employee.expire_time
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Long expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_employee.is_admin
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Integer isAdmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_employee.id
     *
     * @return the value of portal_employee.id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_employee.id
     *
     * @param id the value for portal_employee.id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_employee.user_name
     *
     * @return the value of portal_employee.user_name
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_employee.user_name
     *
     * @param userName the value for portal_employee.user_name
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_employee.password
     *
     * @return the value of portal_employee.password
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_employee.password
     *
     * @param password the value for portal_employee.password
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_employee.name
     *
     * @return the value of portal_employee.name
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_employee.name
     *
     * @param name the value for portal_employee.name
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_employee.mobile
     *
     * @return the value of portal_employee.mobile
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_employee.mobile
     *
     * @param mobile the value for portal_employee.mobile
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_employee.department_id
     *
     * @return the value of portal_employee.department_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_employee.department_id
     *
     * @param departmentId the value for portal_employee.department_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_employee.is_delete
     *
     * @return the value of portal_employee.is_delete
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_employee.is_delete
     *
     * @param isDelete the value for portal_employee.is_delete
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_employee.token
     *
     * @return the value of portal_employee.token
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_employee.token
     *
     * @param token the value for portal_employee.token
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_employee.expire_time
     *
     * @return the value of portal_employee.expire_time
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Long getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_employee.expire_time
     *
     * @param expireTime the value for portal_employee.expire_time
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setExpireTime(Long expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_employee.is_admin
     *
     * @return the value of portal_employee.is_admin
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Integer getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_employee.is_admin
     *
     * @param isAdmin the value for portal_employee.is_admin
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setIsAdmin(Integer isAdmin) {
        this.isAdmin = isAdmin;
    }
}