package com.tbjj.portal.repository.api.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EventStreamExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public EventStreamExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEventIdIsNull() {
            addCriterion("event_id is null");
            return (Criteria) this;
        }

        public Criteria andEventIdIsNotNull() {
            addCriterion("event_id is not null");
            return (Criteria) this;
        }

        public Criteria andEventIdEqualTo(Integer value) {
            addCriterion("event_id =", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotEqualTo(Integer value) {
            addCriterion("event_id <>", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdGreaterThan(Integer value) {
            addCriterion("event_id >", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("event_id >=", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLessThan(Integer value) {
            addCriterion("event_id <", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLessThanOrEqualTo(Integer value) {
            addCriterion("event_id <=", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdIn(List<Integer> values) {
            addCriterion("event_id in", values, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotIn(List<Integer> values) {
            addCriterion("event_id not in", values, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdBetween(Integer value1, Integer value2) {
            addCriterion("event_id between", value1, value2, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotBetween(Integer value1, Integer value2) {
            addCriterion("event_id not between", value1, value2, "eventId");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIsNull() {
            addCriterion("system_code is null");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIsNotNull() {
            addCriterion("system_code is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCodeEqualTo(String value) {
            addCriterion("system_code =", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotEqualTo(String value) {
            addCriterion("system_code <>", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeGreaterThan(String value) {
            addCriterion("system_code >", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeGreaterThanOrEqualTo(String value) {
            addCriterion("system_code >=", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLessThan(String value) {
            addCriterion("system_code <", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLessThanOrEqualTo(String value) {
            addCriterion("system_code <=", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLike(String value) {
            addCriterion("system_code like", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotLike(String value) {
            addCriterion("system_code not like", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIn(List<String> values) {
            addCriterion("system_code in", values, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotIn(List<String> values) {
            addCriterion("system_code not in", values, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeBetween(String value1, String value2) {
            addCriterion("system_code between", value1, value2, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotBetween(String value1, String value2) {
            addCriterion("system_code not between", value1, value2, "systemCode");
            return (Criteria) this;
        }

        public Criteria andOperationTimeIsNull() {
            addCriterion("operation_time is null");
            return (Criteria) this;
        }

        public Criteria andOperationTimeIsNotNull() {
            addCriterion("operation_time is not null");
            return (Criteria) this;
        }

        public Criteria andOperationTimeEqualTo(Date value) {
            addCriterion("operation_time =", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeNotEqualTo(Date value) {
            addCriterion("operation_time <>", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeGreaterThan(Date value) {
            addCriterion("operation_time >", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("operation_time >=", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeLessThan(Date value) {
            addCriterion("operation_time <", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeLessThanOrEqualTo(Date value) {
            addCriterion("operation_time <=", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeIn(List<Date> values) {
            addCriterion("operation_time in", values, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeNotIn(List<Date> values) {
            addCriterion("operation_time not in", values, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeBetween(Date value1, Date value2) {
            addCriterion("operation_time between", value1, value2, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeNotBetween(Date value1, Date value2) {
            addCriterion("operation_time not between", value1, value2, "operationTime");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andApproveResultIsNull() {
            addCriterion("approve_result is null");
            return (Criteria) this;
        }

        public Criteria andApproveResultIsNotNull() {
            addCriterion("approve_result is not null");
            return (Criteria) this;
        }

        public Criteria andApproveResultEqualTo(Integer value) {
            addCriterion("approve_result =", value, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultNotEqualTo(Integer value) {
            addCriterion("approve_result <>", value, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultGreaterThan(Integer value) {
            addCriterion("approve_result >", value, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultGreaterThanOrEqualTo(Integer value) {
            addCriterion("approve_result >=", value, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultLessThan(Integer value) {
            addCriterion("approve_result <", value, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultLessThanOrEqualTo(Integer value) {
            addCriterion("approve_result <=", value, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultIn(List<Integer> values) {
            addCriterion("approve_result in", values, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultNotIn(List<Integer> values) {
            addCriterion("approve_result not in", values, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultBetween(Integer value1, Integer value2) {
            addCriterion("approve_result between", value1, value2, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveResultNotBetween(Integer value1, Integer value2) {
            addCriterion("approve_result not between", value1, value2, "approveResult");
            return (Criteria) this;
        }

        public Criteria andApproveUrlIsNull() {
            addCriterion("approve_url is null");
            return (Criteria) this;
        }

        public Criteria andApproveUrlIsNotNull() {
            addCriterion("approve_url is not null");
            return (Criteria) this;
        }

        public Criteria andApproveUrlEqualTo(String value) {
            addCriterion("approve_url =", value, "approveUrl");
            return (Criteria) this;
        }

        public Criteria andApproveUrlNotEqualTo(String value) {
            addCriterion("approve_url <>", value, "approveUrl");
            return (Criteria) this;
        }

        public Criteria andApproveUrlGreaterThan(String value) {
            addCriterion("approve_url >", value, "approveUrl");
            return (Criteria) this;
        }

        public Criteria andApproveUrlGreaterThanOrEqualTo(String value) {
            addCriterion("approve_url >=", value, "approveUrl");
            return (Criteria) this;
        }

        public Criteria andApproveUrlLessThan(String value) {
            addCriterion("approve_url <", value, "approveUrl");
            return (Criteria) this;
        }

        public Criteria andApproveUrlLessThanOrEqualTo(String value) {
            addCriterion("approve_url <=", value, "approveUrl");
            return (Criteria) this;
        }

        public Criteria andApproveUrlLike(String value) {
            addCriterion("approve_url like", value, "approveUrl");
            return (Criteria) this;
        }

        public Criteria andApproveUrlNotLike(String value) {
            addCriterion("approve_url not like", value, "approveUrl");
            return (Criteria) this;
        }

        public Criteria andApproveUrlIn(List<String> values) {
            addCriterion("approve_url in", values, "approveUrl");
            return (Criteria) this;
        }

        public Criteria andApproveUrlNotIn(List<String> values) {
            addCriterion("approve_url not in", values, "approveUrl");
            return (Criteria) this;
        }

        public Criteria andApproveUrlBetween(String value1, String value2) {
            addCriterion("approve_url between", value1, value2, "approveUrl");
            return (Criteria) this;
        }

        public Criteria andApproveUrlNotBetween(String value1, String value2) {
            addCriterion("approve_url not between", value1, value2, "approveUrl");
            return (Criteria) this;
        }

        public Criteria andReadCodeIsNull() {
            addCriterion("read_code is null");
            return (Criteria) this;
        }

        public Criteria andReadCodeIsNotNull() {
            addCriterion("read_code is not null");
            return (Criteria) this;
        }

        public Criteria andReadCodeEqualTo(Integer value) {
            addCriterion("read_code =", value, "readCode");
            return (Criteria) this;
        }

        public Criteria andReadCodeNotEqualTo(Integer value) {
            addCriterion("read_code <>", value, "readCode");
            return (Criteria) this;
        }

        public Criteria andReadCodeGreaterThan(Integer value) {
            addCriterion("read_code >", value, "readCode");
            return (Criteria) this;
        }

        public Criteria andReadCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("read_code >=", value, "readCode");
            return (Criteria) this;
        }

        public Criteria andReadCodeLessThan(Integer value) {
            addCriterion("read_code <", value, "readCode");
            return (Criteria) this;
        }

        public Criteria andReadCodeLessThanOrEqualTo(Integer value) {
            addCriterion("read_code <=", value, "readCode");
            return (Criteria) this;
        }

        public Criteria andReadCodeIn(List<Integer> values) {
            addCriterion("read_code in", values, "readCode");
            return (Criteria) this;
        }

        public Criteria andReadCodeNotIn(List<Integer> values) {
            addCriterion("read_code not in", values, "readCode");
            return (Criteria) this;
        }

        public Criteria andReadCodeBetween(Integer value1, Integer value2) {
            addCriterion("read_code between", value1, value2, "readCode");
            return (Criteria) this;
        }

        public Criteria andReadCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("read_code not between", value1, value2, "readCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeIsNull() {
            addCriterion("deal_code is null");
            return (Criteria) this;
        }

        public Criteria andDealCodeIsNotNull() {
            addCriterion("deal_code is not null");
            return (Criteria) this;
        }

        public Criteria andDealCodeEqualTo(Integer value) {
            addCriterion("deal_code =", value, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeNotEqualTo(Integer value) {
            addCriterion("deal_code <>", value, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeGreaterThan(Integer value) {
            addCriterion("deal_code >", value, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("deal_code >=", value, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeLessThan(Integer value) {
            addCriterion("deal_code <", value, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeLessThanOrEqualTo(Integer value) {
            addCriterion("deal_code <=", value, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeIn(List<Integer> values) {
            addCriterion("deal_code in", values, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeNotIn(List<Integer> values) {
            addCriterion("deal_code not in", values, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeBetween(Integer value1, Integer value2) {
            addCriterion("deal_code between", value1, value2, "dealCode");
            return (Criteria) this;
        }

        public Criteria andDealCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("deal_code not between", value1, value2, "dealCode");
            return (Criteria) this;
        }

        public Criteria andBacklogIdIsNull() {
            addCriterion("backlog_id is null");
            return (Criteria) this;
        }

        public Criteria andBacklogIdIsNotNull() {
            addCriterion("backlog_id is not null");
            return (Criteria) this;
        }

        public Criteria andBacklogIdEqualTo(String value) {
            addCriterion("backlog_id =", value, "backlogId");
            return (Criteria) this;
        }

        public Criteria andBacklogIdNotEqualTo(String value) {
            addCriterion("backlog_id <>", value, "backlogId");
            return (Criteria) this;
        }

        public Criteria andBacklogIdGreaterThan(String value) {
            addCriterion("backlog_id >", value, "backlogId");
            return (Criteria) this;
        }

        public Criteria andBacklogIdGreaterThanOrEqualTo(String value) {
            addCriterion("backlog_id >=", value, "backlogId");
            return (Criteria) this;
        }

        public Criteria andBacklogIdLessThan(String value) {
            addCriterion("backlog_id <", value, "backlogId");
            return (Criteria) this;
        }

        public Criteria andBacklogIdLessThanOrEqualTo(String value) {
            addCriterion("backlog_id <=", value, "backlogId");
            return (Criteria) this;
        }

        public Criteria andBacklogIdLike(String value) {
            addCriterion("backlog_id like", value, "backlogId");
            return (Criteria) this;
        }

        public Criteria andBacklogIdNotLike(String value) {
            addCriterion("backlog_id not like", value, "backlogId");
            return (Criteria) this;
        }

        public Criteria andBacklogIdIn(List<String> values) {
            addCriterion("backlog_id in", values, "backlogId");
            return (Criteria) this;
        }

        public Criteria andBacklogIdNotIn(List<String> values) {
            addCriterion("backlog_id not in", values, "backlogId");
            return (Criteria) this;
        }

        public Criteria andBacklogIdBetween(String value1, String value2) {
            addCriterion("backlog_id between", value1, value2, "backlogId");
            return (Criteria) this;
        }

        public Criteria andBacklogIdNotBetween(String value1, String value2) {
            addCriterion("backlog_id not between", value1, value2, "backlogId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_event_stream
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 04 17:35:02 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_event_stream
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}