package com.tbjj.portal.repository.api.entity;

import java.util.Date;

public class EventMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_message.mess_id
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    private Integer messId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_message.event_stream_id
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    private Integer eventStreamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_message.mess_title
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    private String messTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_message.mess_url
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    private String messUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_message.mess_date
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    private Date messDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_message.user_name
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_message.mess_status
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    private Integer messStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_message.is_delete
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_message.mess_id
     *
     * @return the value of portal_event_message.mess_id
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public Integer getMessId() {
        return messId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_message.mess_id
     *
     * @param messId the value for portal_event_message.mess_id
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public void setMessId(Integer messId) {
        this.messId = messId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_message.event_stream_id
     *
     * @return the value of portal_event_message.event_stream_id
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public Integer getEventStreamId() {
        return eventStreamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_message.event_stream_id
     *
     * @param eventStreamId the value for portal_event_message.event_stream_id
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public void setEventStreamId(Integer eventStreamId) {
        this.eventStreamId = eventStreamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_message.mess_title
     *
     * @return the value of portal_event_message.mess_title
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public String getMessTitle() {
        return messTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_message.mess_title
     *
     * @param messTitle the value for portal_event_message.mess_title
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public void setMessTitle(String messTitle) {
        this.messTitle = messTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_message.mess_url
     *
     * @return the value of portal_event_message.mess_url
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public String getMessUrl() {
        return messUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_message.mess_url
     *
     * @param messUrl the value for portal_event_message.mess_url
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public void setMessUrl(String messUrl) {
        this.messUrl = messUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_message.mess_date
     *
     * @return the value of portal_event_message.mess_date
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public Date getMessDate() {
        return messDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_message.mess_date
     *
     * @param messDate the value for portal_event_message.mess_date
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public void setMessDate(Date messDate) {
        this.messDate = messDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_message.user_name
     *
     * @return the value of portal_event_message.user_name
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_message.user_name
     *
     * @param userName the value for portal_event_message.user_name
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_message.mess_status
     *
     * @return the value of portal_event_message.mess_status
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public Integer getMessStatus() {
        return messStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_message.mess_status
     *
     * @param messStatus the value for portal_event_message.mess_status
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public void setMessStatus(Integer messStatus) {
        this.messStatus = messStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_message.is_delete
     *
     * @return the value of portal_event_message.is_delete
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_message.is_delete
     *
     * @param isDelete the value for portal_event_message.is_delete
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}