package com.tbjj.portal.repository.api.entity;

import java.util.Date;

public class EventStream {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_stream.id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_stream.event_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Integer eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_stream.system_code
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private String systemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_stream.operation_time
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Date operationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_stream.user_name
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_stream.approve_result
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Integer approveResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_stream.approve_url
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private String approveUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_stream.read_code
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Integer readCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_stream.deal_code
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Integer dealCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_stream.backlog_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private String backlogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_event_stream.response_desc
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private String responseDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_stream.id
     *
     * @return the value of portal_event_stream.id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_stream.id
     *
     * @param id the value for portal_event_stream.id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_stream.event_id
     *
     * @return the value of portal_event_stream.event_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_stream.event_id
     *
     * @param eventId the value for portal_event_stream.event_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_stream.system_code
     *
     * @return the value of portal_event_stream.system_code
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public String getSystemCode() {
        return systemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_stream.system_code
     *
     * @param systemCode the value for portal_event_stream.system_code
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setSystemCode(String systemCode) {
        this.systemCode = systemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_stream.operation_time
     *
     * @return the value of portal_event_stream.operation_time
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_stream.operation_time
     *
     * @param operationTime the value for portal_event_stream.operation_time
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_stream.user_name
     *
     * @return the value of portal_event_stream.user_name
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_stream.user_name
     *
     * @param userName the value for portal_event_stream.user_name
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_stream.approve_result
     *
     * @return the value of portal_event_stream.approve_result
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Integer getApproveResult() {
        return approveResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_stream.approve_result
     *
     * @param approveResult the value for portal_event_stream.approve_result
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setApproveResult(Integer approveResult) {
        this.approveResult = approveResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_stream.approve_url
     *
     * @return the value of portal_event_stream.approve_url
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public String getApproveUrl() {
        return approveUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_stream.approve_url
     *
     * @param approveUrl the value for portal_event_stream.approve_url
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setApproveUrl(String approveUrl) {
        this.approveUrl = approveUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_stream.read_code
     *
     * @return the value of portal_event_stream.read_code
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Integer getReadCode() {
        return readCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_stream.read_code
     *
     * @param readCode the value for portal_event_stream.read_code
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setReadCode(Integer readCode) {
        this.readCode = readCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_stream.deal_code
     *
     * @return the value of portal_event_stream.deal_code
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Integer getDealCode() {
        return dealCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_stream.deal_code
     *
     * @param dealCode the value for portal_event_stream.deal_code
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setDealCode(Integer dealCode) {
        this.dealCode = dealCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_stream.backlog_id
     *
     * @return the value of portal_event_stream.backlog_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public String getBacklogId() {
        return backlogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_stream.backlog_id
     *
     * @param backlogId the value for portal_event_stream.backlog_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setBacklogId(String backlogId) {
        this.backlogId = backlogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_event_stream.response_desc
     *
     * @return the value of portal_event_stream.response_desc
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public String getResponseDesc() {
        return responseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_event_stream.response_desc
     *
     * @param responseDesc the value for portal_event_stream.response_desc
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setResponseDesc(String responseDesc) {
        this.responseDesc = responseDesc;
    }
}