package com.tbjj.portal.repository.api.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EventMessageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public EventMessageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMessIdIsNull() {
            addCriterion("mess_id is null");
            return (Criteria) this;
        }

        public Criteria andMessIdIsNotNull() {
            addCriterion("mess_id is not null");
            return (Criteria) this;
        }

        public Criteria andMessIdEqualTo(Integer value) {
            addCriterion("mess_id =", value, "messId");
            return (Criteria) this;
        }

        public Criteria andMessIdNotEqualTo(Integer value) {
            addCriterion("mess_id <>", value, "messId");
            return (Criteria) this;
        }

        public Criteria andMessIdGreaterThan(Integer value) {
            addCriterion("mess_id >", value, "messId");
            return (Criteria) this;
        }

        public Criteria andMessIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mess_id >=", value, "messId");
            return (Criteria) this;
        }

        public Criteria andMessIdLessThan(Integer value) {
            addCriterion("mess_id <", value, "messId");
            return (Criteria) this;
        }

        public Criteria andMessIdLessThanOrEqualTo(Integer value) {
            addCriterion("mess_id <=", value, "messId");
            return (Criteria) this;
        }

        public Criteria andMessIdIn(List<Integer> values) {
            addCriterion("mess_id in", values, "messId");
            return (Criteria) this;
        }

        public Criteria andMessIdNotIn(List<Integer> values) {
            addCriterion("mess_id not in", values, "messId");
            return (Criteria) this;
        }

        public Criteria andMessIdBetween(Integer value1, Integer value2) {
            addCriterion("mess_id between", value1, value2, "messId");
            return (Criteria) this;
        }

        public Criteria andMessIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mess_id not between", value1, value2, "messId");
            return (Criteria) this;
        }

        public Criteria andEventStreamIdIsNull() {
            addCriterion("event_stream_id is null");
            return (Criteria) this;
        }

        public Criteria andEventStreamIdIsNotNull() {
            addCriterion("event_stream_id is not null");
            return (Criteria) this;
        }

        public Criteria andEventStreamIdEqualTo(Integer value) {
            addCriterion("event_stream_id =", value, "eventStreamId");
            return (Criteria) this;
        }

        public Criteria andEventStreamIdNotEqualTo(Integer value) {
            addCriterion("event_stream_id <>", value, "eventStreamId");
            return (Criteria) this;
        }

        public Criteria andEventStreamIdGreaterThan(Integer value) {
            addCriterion("event_stream_id >", value, "eventStreamId");
            return (Criteria) this;
        }

        public Criteria andEventStreamIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("event_stream_id >=", value, "eventStreamId");
            return (Criteria) this;
        }

        public Criteria andEventStreamIdLessThan(Integer value) {
            addCriterion("event_stream_id <", value, "eventStreamId");
            return (Criteria) this;
        }

        public Criteria andEventStreamIdLessThanOrEqualTo(Integer value) {
            addCriterion("event_stream_id <=", value, "eventStreamId");
            return (Criteria) this;
        }

        public Criteria andEventStreamIdIn(List<Integer> values) {
            addCriterion("event_stream_id in", values, "eventStreamId");
            return (Criteria) this;
        }

        public Criteria andEventStreamIdNotIn(List<Integer> values) {
            addCriterion("event_stream_id not in", values, "eventStreamId");
            return (Criteria) this;
        }

        public Criteria andEventStreamIdBetween(Integer value1, Integer value2) {
            addCriterion("event_stream_id between", value1, value2, "eventStreamId");
            return (Criteria) this;
        }

        public Criteria andEventStreamIdNotBetween(Integer value1, Integer value2) {
            addCriterion("event_stream_id not between", value1, value2, "eventStreamId");
            return (Criteria) this;
        }

        public Criteria andMessTitleIsNull() {
            addCriterion("mess_title is null");
            return (Criteria) this;
        }

        public Criteria andMessTitleIsNotNull() {
            addCriterion("mess_title is not null");
            return (Criteria) this;
        }

        public Criteria andMessTitleEqualTo(String value) {
            addCriterion("mess_title =", value, "messTitle");
            return (Criteria) this;
        }

        public Criteria andMessTitleNotEqualTo(String value) {
            addCriterion("mess_title <>", value, "messTitle");
            return (Criteria) this;
        }

        public Criteria andMessTitleGreaterThan(String value) {
            addCriterion("mess_title >", value, "messTitle");
            return (Criteria) this;
        }

        public Criteria andMessTitleGreaterThanOrEqualTo(String value) {
            addCriterion("mess_title >=", value, "messTitle");
            return (Criteria) this;
        }

        public Criteria andMessTitleLessThan(String value) {
            addCriterion("mess_title <", value, "messTitle");
            return (Criteria) this;
        }

        public Criteria andMessTitleLessThanOrEqualTo(String value) {
            addCriterion("mess_title <=", value, "messTitle");
            return (Criteria) this;
        }

        public Criteria andMessTitleLike(String value) {
            addCriterion("mess_title like", value, "messTitle");
            return (Criteria) this;
        }

        public Criteria andMessTitleNotLike(String value) {
            addCriterion("mess_title not like", value, "messTitle");
            return (Criteria) this;
        }

        public Criteria andMessTitleIn(List<String> values) {
            addCriterion("mess_title in", values, "messTitle");
            return (Criteria) this;
        }

        public Criteria andMessTitleNotIn(List<String> values) {
            addCriterion("mess_title not in", values, "messTitle");
            return (Criteria) this;
        }

        public Criteria andMessTitleBetween(String value1, String value2) {
            addCriterion("mess_title between", value1, value2, "messTitle");
            return (Criteria) this;
        }

        public Criteria andMessTitleNotBetween(String value1, String value2) {
            addCriterion("mess_title not between", value1, value2, "messTitle");
            return (Criteria) this;
        }

        public Criteria andMessUrlIsNull() {
            addCriterion("mess_url is null");
            return (Criteria) this;
        }

        public Criteria andMessUrlIsNotNull() {
            addCriterion("mess_url is not null");
            return (Criteria) this;
        }

        public Criteria andMessUrlEqualTo(String value) {
            addCriterion("mess_url =", value, "messUrl");
            return (Criteria) this;
        }

        public Criteria andMessUrlNotEqualTo(String value) {
            addCriterion("mess_url <>", value, "messUrl");
            return (Criteria) this;
        }

        public Criteria andMessUrlGreaterThan(String value) {
            addCriterion("mess_url >", value, "messUrl");
            return (Criteria) this;
        }

        public Criteria andMessUrlGreaterThanOrEqualTo(String value) {
            addCriterion("mess_url >=", value, "messUrl");
            return (Criteria) this;
        }

        public Criteria andMessUrlLessThan(String value) {
            addCriterion("mess_url <", value, "messUrl");
            return (Criteria) this;
        }

        public Criteria andMessUrlLessThanOrEqualTo(String value) {
            addCriterion("mess_url <=", value, "messUrl");
            return (Criteria) this;
        }

        public Criteria andMessUrlLike(String value) {
            addCriterion("mess_url like", value, "messUrl");
            return (Criteria) this;
        }

        public Criteria andMessUrlNotLike(String value) {
            addCriterion("mess_url not like", value, "messUrl");
            return (Criteria) this;
        }

        public Criteria andMessUrlIn(List<String> values) {
            addCriterion("mess_url in", values, "messUrl");
            return (Criteria) this;
        }

        public Criteria andMessUrlNotIn(List<String> values) {
            addCriterion("mess_url not in", values, "messUrl");
            return (Criteria) this;
        }

        public Criteria andMessUrlBetween(String value1, String value2) {
            addCriterion("mess_url between", value1, value2, "messUrl");
            return (Criteria) this;
        }

        public Criteria andMessUrlNotBetween(String value1, String value2) {
            addCriterion("mess_url not between", value1, value2, "messUrl");
            return (Criteria) this;
        }

        public Criteria andMessDateIsNull() {
            addCriterion("mess_date is null");
            return (Criteria) this;
        }

        public Criteria andMessDateIsNotNull() {
            addCriterion("mess_date is not null");
            return (Criteria) this;
        }

        public Criteria andMessDateEqualTo(Date value) {
            addCriterion("mess_date =", value, "messDate");
            return (Criteria) this;
        }

        public Criteria andMessDateNotEqualTo(Date value) {
            addCriterion("mess_date <>", value, "messDate");
            return (Criteria) this;
        }

        public Criteria andMessDateGreaterThan(Date value) {
            addCriterion("mess_date >", value, "messDate");
            return (Criteria) this;
        }

        public Criteria andMessDateGreaterThanOrEqualTo(Date value) {
            addCriterion("mess_date >=", value, "messDate");
            return (Criteria) this;
        }

        public Criteria andMessDateLessThan(Date value) {
            addCriterion("mess_date <", value, "messDate");
            return (Criteria) this;
        }

        public Criteria andMessDateLessThanOrEqualTo(Date value) {
            addCriterion("mess_date <=", value, "messDate");
            return (Criteria) this;
        }

        public Criteria andMessDateIn(List<Date> values) {
            addCriterion("mess_date in", values, "messDate");
            return (Criteria) this;
        }

        public Criteria andMessDateNotIn(List<Date> values) {
            addCriterion("mess_date not in", values, "messDate");
            return (Criteria) this;
        }

        public Criteria andMessDateBetween(Date value1, Date value2) {
            addCriterion("mess_date between", value1, value2, "messDate");
            return (Criteria) this;
        }

        public Criteria andMessDateNotBetween(Date value1, Date value2) {
            addCriterion("mess_date not between", value1, value2, "messDate");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andMessStatusIsNull() {
            addCriterion("mess_status is null");
            return (Criteria) this;
        }

        public Criteria andMessStatusIsNotNull() {
            addCriterion("mess_status is not null");
            return (Criteria) this;
        }

        public Criteria andMessStatusEqualTo(Integer value) {
            addCriterion("mess_status =", value, "messStatus");
            return (Criteria) this;
        }

        public Criteria andMessStatusNotEqualTo(Integer value) {
            addCriterion("mess_status <>", value, "messStatus");
            return (Criteria) this;
        }

        public Criteria andMessStatusGreaterThan(Integer value) {
            addCriterion("mess_status >", value, "messStatus");
            return (Criteria) this;
        }

        public Criteria andMessStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("mess_status >=", value, "messStatus");
            return (Criteria) this;
        }

        public Criteria andMessStatusLessThan(Integer value) {
            addCriterion("mess_status <", value, "messStatus");
            return (Criteria) this;
        }

        public Criteria andMessStatusLessThanOrEqualTo(Integer value) {
            addCriterion("mess_status <=", value, "messStatus");
            return (Criteria) this;
        }

        public Criteria andMessStatusIn(List<Integer> values) {
            addCriterion("mess_status in", values, "messStatus");
            return (Criteria) this;
        }

        public Criteria andMessStatusNotIn(List<Integer> values) {
            addCriterion("mess_status not in", values, "messStatus");
            return (Criteria) this;
        }

        public Criteria andMessStatusBetween(Integer value1, Integer value2) {
            addCriterion("mess_status between", value1, value2, "messStatus");
            return (Criteria) this;
        }

        public Criteria andMessStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("mess_status not between", value1, value2, "messStatus");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Byte value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Byte value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Byte value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Byte value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Byte value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Byte> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Byte> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Byte value1, Byte value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Byte value1, Byte value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_event_message
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 16 08:51:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portal_event_message
     *
     * @mbg.generated Tue Jan 16 08:51:10 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}