package com.tbjj.portal.repository.api.entity;

public class NaviEmp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_navi_emp.id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_navi_emp.employee_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_navi_emp.navi_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Integer naviId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_navi_emp.is_delete
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_navi_emp.id
     *
     * @return the value of portal_navi_emp.id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_navi_emp.id
     *
     * @param id the value for portal_navi_emp.id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_navi_emp.employee_id
     *
     * @return the value of portal_navi_emp.employee_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_navi_emp.employee_id
     *
     * @param employeeId the value for portal_navi_emp.employee_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_navi_emp.navi_id
     *
     * @return the value of portal_navi_emp.navi_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Integer getNaviId() {
        return naviId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_navi_emp.navi_id
     *
     * @param naviId the value for portal_navi_emp.navi_id
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setNaviId(Integer naviId) {
        this.naviId = naviId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_navi_emp.is_delete
     *
     * @return the value of portal_navi_emp.is_delete
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_navi_emp.is_delete
     *
     * @param isDelete the value for portal_navi_emp.is_delete
     *
     * @mbg.generated Thu Jan 04 17:35:02 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}