package com.tbjj.portal.repository.api.entity;

import java.util.Date;

public class Panel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel.id
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel.name
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel.department_id
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel.yaxis
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    private String yaxis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel.create_time
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel.update_time
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel.employee_id
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel.is_delete
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel.inco_url
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    private String incoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel.panel_type
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    private Integer panelType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel.id
     *
     * @return the value of portal_panel.id
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel.id
     *
     * @param id the value for portal_panel.id
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel.name
     *
     * @return the value of portal_panel.name
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel.name
     *
     * @param name the value for portal_panel.name
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel.department_id
     *
     * @return the value of portal_panel.department_id
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel.department_id
     *
     * @param departmentId the value for portal_panel.department_id
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel.yaxis
     *
     * @return the value of portal_panel.yaxis
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public String getYaxis() {
        return yaxis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel.yaxis
     *
     * @param yaxis the value for portal_panel.yaxis
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public void setYaxis(String yaxis) {
        this.yaxis = yaxis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel.create_time
     *
     * @return the value of portal_panel.create_time
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel.create_time
     *
     * @param createTime the value for portal_panel.create_time
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel.update_time
     *
     * @return the value of portal_panel.update_time
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel.update_time
     *
     * @param updateTime the value for portal_panel.update_time
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel.employee_id
     *
     * @return the value of portal_panel.employee_id
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel.employee_id
     *
     * @param employeeId the value for portal_panel.employee_id
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel.is_delete
     *
     * @return the value of portal_panel.is_delete
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel.is_delete
     *
     * @param isDelete the value for portal_panel.is_delete
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel.inco_url
     *
     * @return the value of portal_panel.inco_url
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public String getIncoUrl() {
        return incoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel.inco_url
     *
     * @param incoUrl the value for portal_panel.inco_url
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public void setIncoUrl(String incoUrl) {
        this.incoUrl = incoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel.panel_type
     *
     * @return the value of portal_panel.panel_type
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public Integer getPanelType() {
        return panelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel.panel_type
     *
     * @param panelType the value for portal_panel.panel_type
     *
     * @mbg.generated Mon Jan 08 18:56:23 CST 2018
     */
    public void setPanelType(Integer panelType) {
        this.panelType = panelType;
    }
}