package com.tbjj.portal.repository.api.entity;

public class PanelEmp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel_emp.id
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel_emp.employee_id
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel_emp.panel_id
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    private Integer panelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel_emp.location
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    private Integer location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portal_panel_emp.is_delete
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel_emp.id
     *
     * @return the value of portal_panel_emp.id
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel_emp.id
     *
     * @param id the value for portal_panel_emp.id
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel_emp.employee_id
     *
     * @return the value of portal_panel_emp.employee_id
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel_emp.employee_id
     *
     * @param employeeId the value for portal_panel_emp.employee_id
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel_emp.panel_id
     *
     * @return the value of portal_panel_emp.panel_id
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    public Integer getPanelId() {
        return panelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel_emp.panel_id
     *
     * @param panelId the value for portal_panel_emp.panel_id
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    public void setPanelId(Integer panelId) {
        this.panelId = panelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel_emp.location
     *
     * @return the value of portal_panel_emp.location
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    public Integer getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel_emp.location
     *
     * @param location the value for portal_panel_emp.location
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    public void setLocation(Integer location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portal_panel_emp.is_delete
     *
     * @return the value of portal_panel_emp.is_delete
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portal_panel_emp.is_delete
     *
     * @param isDelete the value for portal_panel_emp.is_delete
     *
     * @mbg.generated Mon Jan 08 18:21:16 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}